### ISSUE TITLE
Infinite loop for new account that requires an alternate email/phone

### ISSUE THREAD

**Issue by heximing** [farshadz1997/Microsoft-Rewards-bot#219]
![20230404234513](https://user-images.githubusercontent.com/541861/229976265-62265838-a553-4dcd-90c2-ee99e0bcba86.png)

If the account requires protection by Microsoft as shown in the above picture, the farmer will enter infinite loop like below:

```
[FLAGS] headless: True
[FLAGS] error: True
[FLAGS] superfast: True
[FLAGS] edge: True
[FLAGS] skip_unusual: True
[FLAGS] no_images: True
[FLAGS] currency: USD
[FLAGS] dont_check_for_updates: True

[LOGS] Logs loaded successfully.

********************t6172996924@hotmail.com********************

DevTools listening on ws://127.0.0.1:52657/devtools/browser/8436ebe9-7ed7-44ab-9f30-2501fcb55ed9
[LOGIN] Logging-in...
Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2354, in farmer
    login(browser, account['username'], account['password'])
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 222, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 493, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\D\Python\WPy64-31080\python-3.10.8.amd64\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6A389A742+12658]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A38329E2+747650]
        (No symbol) [0x00007FF6A34CDD2E]
        (No symbol) [0x00007FF6A350FB49]
        (No symbol) [0x00007FF6A350FCD0]
        (No symbol) [0x00007FF6A354B4B7]
        (No symbol) [0x00007FF6A352F42F]
        (No symbol) [0x00007FF6A3502791]
        (No symbol) [0x00007FF6A354874C]
        (No symbol) [0x00007FF6A352F1C3]
        (No symbol) [0x00007FF6A35017D6]
        (No symbol) [0x00007FF6A35009B5]
        (No symbol) [0x00007FF6A3501F44]
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6A37456A0+147088]
        (No symbol) [0x00007FF6A35E9306]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A3784607+33959]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A37880D5+49013]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6A3A79A93+1305267]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A383AF9C+781884]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A38404C4+803684]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A384061C+804028]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A3848721+837057]
        BaseThreadInitThunk [0x00007FFFE6CF7614+20]
        RtlUserThreadStart [0x00007FFFE81A26A1+33]



********************t6172996924@hotmail.com********************

DevTools listening on ws://127.0.0.1:52723/devtools/browser/93ffe8eb-8326-4bb8-9af1-385f5bccff69
[LOGIN] Logging-in...
Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2354, in farmer
    login(browser, account['username'], account['password'])
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 222, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 493, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\D\Python\WPy64-31080\python-3.10.8.amd64\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6A389A742+12658]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A38329E2+747650]
        (No symbol) [0x00007FF6A34CDD2E]
        (No symbol) [0x00007FF6A350FB49]
        (No symbol) [0x00007FF6A350FCD0]
        (No symbol) [0x00007FF6A354B4B7]
        (No symbol) [0x00007FF6A352F42F]
        (No symbol) [0x00007FF6A3502791]
        (No symbol) [0x00007FF6A354874C]
        (No symbol) [0x00007FF6A352F1C3]
        (No symbol) [0x00007FF6A35017D6]
        (No symbol) [0x00007FF6A35009B5]
        (No symbol) [0x00007FF6A3501F44]
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6A37456A0+147088]
        (No symbol) [0x00007FF6A35E9306]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A3784607+33959]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A37880D5+49013]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6A3A79A93+1305267]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A383AF9C+781884]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A38404C4+803684]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A384061C+804028]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A3848721+837057]
        BaseThreadInitThunk [0x00007FFFE6CF7614+20]
        RtlUserThreadStart [0x00007FFFE81A26A1+33]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2354, in farmer
    login(browser, account['username'], account['password'])
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 222, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 493, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\D\Python\WPy64-31080\python-3.10.8.amd64\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6A389A742+12658]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A38329E2+747650]
        (No symbol) [0x00007FF6A34CDD2E]
        (No symbol) [0x00007FF6A350FB49]
        (No symbol) [0x00007FF6A350FCD0]
        (No symbol) [0x00007FF6A354B4B7]
        (No symbol) [0x00007FF6A352F42F]
        (No symbol) [0x00007FF6A3502791]
        (No symbol) [0x00007FF6A354874C]
        (No symbol) [0x00007FF6A352F1C3]
        (No symbol) [0x00007FF6A35017D6]
        (No symbol) [0x00007FF6A35009B5]
        (No symbol) [0x00007FF6A3501F44]
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6A37456A0+147088]
        (No symbol) [0x00007FF6A35E9306]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A3784607+33959]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A37880D5+49013]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6A3A79A93+1305267]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A383AF9C+781884]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A38404C4+803684]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A384061C+804028]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6A3848721+837057]
        BaseThreadInitThunk [0x00007FFFE6CF7614+20]
        RtlUserThreadStart [0x00007FFFE81A26A1+33]

```

**Comment by AG4lyf** [comment]
an account is needed to fix this. 
a temporary fix was given but it was not working and there was no way to test if its working or not as we don't have the adequate account for it

**Comment by AG4lyf** [comment]
Related #163  and #202

**Comment by AG4lyf** [comment]
Have you tried the `--skip-unusual ` flag ?

**Comment by PttsDev** [comment]
Same issue using ``--skip-unusual`` flag 
My message said 6 days instead of 5 but i suppose that's not causing the issue

**Comment by farshadz1997** [comment]
I pushed another fix for this, have you tried it?

**Comment by heximing** [comment]
I use the latest code, but the problem still exists.

In addition, I found out that it is not related to the account, but related to Edge. I use 
--headless --error --superfast --no-images --dont-check-for-updates --skip-unusual --edge --currency USD

If the code works, I usually do not come here to update the code. I used an old version where I need to manually download the Chrome or Edge driver and put them in Windows folder. It worked well until yesterday I come here and update the code.

By the way, now the code automatically download the Chrome or Edge drivers (I deleted the ones in Windows folder), but where is the driver located? I could not find it in Windows folder.

**Comment by farshadz1997** [comment]
I don't know where it does save the Webdriver, you can still use your downloaded Webdriver by adding ```--no-webdriver-manager```.
you mean it's working on chrome?

**Comment by PttsDev** [comment]
I don't think he means that cause I use Chrome but it still didn't work, I've clicked it manually for now, so I'll update if the error happens again

**Comment by AG4lyf** [comment]
if you click the skip button 
the prompt stops coming for the day as the prompt says 

you have to wait till you get the prompt next day

**Comment by heximing** [comment]
> I don't know where it does save the Webdriver, you can still use your downloaded Webdriver by adding `--no-webdriver-manager`. you mean it's working on chrome?

It works for me if I use default (Chrome). It does not work if I use --edge.

I suspect maybe I used the wrong driver or the code downloaded the wrong driver. So I asked where does not driver stored when the code automatically downloads the driver.

**Comment by heximing** [comment]
> if you click the skip button the prompt stops coming for the day as the prompt says
> 
> you have to wait till you get the prompt next day

I do not know where you mean the "skip button". I use command line to run the code in Windows. I do not use any IDE.

**Comment by heximing** [comment]
I am pretty sure is NOT webdriver-manager's problem because I use --no-webdriver-manager and download the edge driver manually, and it still has the same error. 

Using Chrome does not have problem. Usually a very old version code using --edge has no problem. Therefore, there might be something wrong when using edge driver to run the code.

**Comment by eperitus** [comment]
I'm seeing something similar with --edge.  Instead of "Help us protect your account", the login screen tells me I'm logged in and displays a message about sync.  The farmer then just keeps looping and signing in over and over, seemingly without recognizing it's actually already signed in.

It would be nice to be able to use an already signed in account and skip the whole auth process.  Is that possible?

**Comment by AG4lyf** [comment]
![image](https://user-images.githubusercontent.com/45149585/232460181-11388952-abef-4a1e-b4f4-3e0bd510c53c.png)
the prompt doesn't stop anything happen in background. 
only thing is we should be checcking if there's an already an account logged in
log out 
and then log in with the account.

**Comment by eperitus** [comment]
I tried logging out and logging in (in edge), and reran the latest version of the script.  

Same looping problem.

I ran it with --error this time, and this is the output:

```
DevTools listening on ws://127.0.0.1:56088/devtools/browser/430248a7-ffa0-4955-ace8-4dc53f785f06
[LOGIN] Logging-in...
Traceback (most recent call last):
  File "C:\Users\-\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 2647, in farmer
    login(browser, account['username'], account['password'], account.get(
  File "C:\Users\-\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 304, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\Users\-\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 632, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF70F7DDF52+60274]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F76EBB2+818866]
        (No symbol) [0x00007FF70F3FDFAE]
        (No symbol) [0x00007FF70F43FAA1]
        (No symbol) [0x00007FF70F43FC28]
        (No symbol) [0x00007FF70F47B687]
        (No symbol) [0x00007FF70F45F5AF]
        (No symbol) [0x00007FF70F432751]
        (No symbol) [0x00007FF70F47891C]
        (No symbol) [0x00007FF70F45F343]
        (No symbol) [0x00007FF70F431796]
        (No symbol) [0x00007FF70F430975]
        (No symbol) [0x00007FF70F431F04]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF70F6727E7+1593703]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF70F51AC6D+185837]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F6AFD57+36951]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F6A7E65+4453]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF70F9AFD73+1319011]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F776C6C+851820]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F772CD4+835540]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F772E2C+835884]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F768A01+793857]
        BaseThreadInitThunk [0x00007FFC32A926BD+29]
        RtlUserThreadStart [0x00007FFC347AA9F8+40]
```

Chrome works fine.

**Comment by Small-Ku** [comment]
> ![image](https://user-images.githubusercontent.com/45149585/232460181-11388952-abef-4a1e-b4f4-3e0bd510c53c.png) the prompt doesn't stop anything happen in background. only thing is we should be checcking if there's an already an account logged in log out and then log in with the account.

This check is already available when ARGS.session is true. It is fixed after enabling this flag.
